### ISSUE TITLE
Template Generator not working

### ISSUE THREAD

**Issue by ryansena** [OpenCerts/admin-website#100]
GovTech's tools to generate template in our development machine : 
npm run dev-cli
works till it prompts:
? Organisation Domain Name? e.g: moe.edu.sg
it just hang there, no input accepted.
Any advice?

Tried created the templates and inserting subfolders in the folder under:
...opencerts-website\src\components\CertificateTemplates\tlds\sg\edu
and amended the index.js in this folder

it compiles Okay
But the template is not used, only the default is used

**Comment by yehjxraymond** [comment]
Could you explain what is your expected outcome and what is the observed outcome?

**Comment by ryansena** [comment]
> Could you explain what is your expected outcome and what is the observed outcome?

expected outcome: the script promtps: ? _Organisation Domain Name? e.g: moe.edu.sg_
we expect it would accept input, we actually key our : sp.edu.sg but the input is not reflex on screen

observed outcome: the script is stuck at the prompts, we actually wait 8 hours, still stuck. so eventually we close the script.

**Comment by yehjxraymond** [comment]
Just to confirm, can you try hitting the enter key after it runs? We sometime see problems with interactive prompts on Windows

**Comment by ryansena** [comment]
yes we did

**Comment by yehjxraymond** [comment]
Hi, the tool is currently deprecated in view of v2.0. For legacy templates, you may follow how the other institutes are doing it now.
