### ISSUE TITLE
how to add a new institution into the version 2 renderer?

### ISSUE THREAD

**Issue by ryansena** [OpenCerts/admin-website#122]
We have installed the the version 2 renderer in June.
To add the sp template
We created the sp sub-folder in the path:
C:\GovTech\OpenCert_Site\06_20\opencerts-website\src\components\CertificateTemplates\tlds\sg\edu
beside the other folders: ite, np, nyp, rp, singaporetech, tp
and amended the file index.js to add the lines for sp import and addDirToTemplatePath.
we bring in the template done in the eralier version in this sp sub-folder, and done some changes to the js files in our sp folder to correct the compliation error.

However the web-based view (localhost:3000/viewer) keep showing “Institution no in Registry” and the certificate is displayed using the default template.  I believe we must have missed some steps such that our template is being used.  On this we seek you help.

Please guide us

**Comment by yehjxraymond** [comment]
Could you send in a pull request so we have a look. Fork the legacy repo, then make the necessary changes on your own fork and then submit a pull request from your fork to us.

**Comment by yehjxraymond** [comment]
Also to clarify, that is not v2 of the renderer. That’s the legacy templates.

**Comment by ryansena** [comment]
We have tried to fork and PR this same project
OpenCerts/legacy-templates@e294c51 : 
https://github.com/OpenCerts/legacy-templates/commit/e294c51480922c3787b9d5bcebb9dbd49fe61084

in the previous issue track.  Seemingly it was not done properly. 
That's a harder problem for me to tackle, is there an alternative to that?

**Comment by ryansena** [comment]
Phew! created the PR in https://github.com/OpenCerts/legacy-templates/pull/10

**Comment by ryansena** [comment]
the Pull request is created in OpenCerts/legacy-templates
pls review

**Comment by rjchow** [comment]
hi sorry for the delay will review this by end of day tomorrow
