### ISSUE TITLE
Fresh Clone: SyntaxError: Unexpected identifier (anonymous function) /admin-website/node_modules/react-spinners/dist/index.js:1

### ISSUE THREAD

**Issue by AdamJLemmon** [OpenCerts/admin-website#141]
I have cloned a fresh instance of the repo and receiving the following error when initially trying to render: `SyntaxError: Unexpected identifier (anonymous function) /admin-website/node_modules/react-spinners/dist/index.js:1`

Steps to reproduce:
1. `git clone git@github.com:OpenCerts/admin-website.git`
2. `yarn`
3. `yarn dev`
4. navigate to localhost:3000 in browser

**Environment**
* ubuntu 16.04
* node v10.13
* google chrome

**Comment by rjchow** [comment]
Try using npm instead of yarn, we switched to npm awhile back

**Comment by AdamJLemmon** [comment]
That resolved it thanks!
