### ISSUE TITLE
Issuing on Ropsten: Certificate issuer identity invalid => Merkle Root Hash?

### ISSUE THREAD

**Issue by AdamJLemmon** [OpenCerts/admin-website#142]
Note I am running everything locally, admin site as well as verification page.

* [Metamask ropsten account](https://ropsten.etherscan.io/address/0x9cb47a806ac793ce9739dd138be3b9deb16c14e4)

* via the admin page I created the store: address: `0x7e09d935E322d370480bFCe8789fA0E291883fD8` and [creation tx](https://ropsten.etherscan.io/tx/0x528564e4e204a955d16bd5868ba324fd1525a92596bc3b2a20bda9a48f73d4ad)

* Then I wanted to issue a cert but only see the option to issue batch in the ui and it requires a merkle root hash.  Can you advise where this should be generated? 

I noticed a merkle root is generated in using the CLI to issue a cert so tried the following.

Certificate template:
```
{
    "id": "2018091259",
    "name": "Certificate",
    "issuedOn": "2018-08-31T23:59:32+08:00",
    "issuers": [
      {
        "name": "BLG",
        "certificateStore": "0x7e09d935E322d370480bFCe8789fA0E291883fD8"
      }
    ],
    "recipient": {
      "name": "Adam Lemmon",
      "email": "johnsnow@gmail.com",
      "phone": "+6588888888"
    },
    "transcript": [
      {
        "name": "BLG",
        "grade": "A",
        "courseCredit": 1,
        "courseCode": "001"
      }
    ],
    "additionalData": {}
  }
```

* successfully issued via the CLI and returned merkle root of `1f7e6b196f240fe5fcd4d46430f97759edd9dc9f9ce45a2cd959a6cb178d886f` then used that to issue the certificate in the ui which seemed to work with this [transaction](https://ropsten.etherscan.io/tx/0x0aa782bb81755b038d432e3ea82a1489514be7068bc1401df55b33b3e574df14)

* Note I have also manually set `IS_MAINNET` to false to the network is noted as `INFURA_ROPSTEN`  but when the generated opencert file is dragged into dropzone the response is `Certificate issuer identity invalid`

**Comment by yehjxraymond** [comment]
You've not verified your identity. Please see https://docs.opencerts.io/dns_verification.html

**Comment by AdamJLemmon** [comment]
This will work for Ropsten as well `netId=3` ?

**Comment by yehjxraymond** [comment]
yep netId is the network that that claim is valid for. 1 is for mainnet, 3 is for ropsten. You will need to have a separate line if you want to enable it for mainnet.

**Comment by yehjxraymond** [comment]
You will use the store address for the record
