### ISSUE TITLE
security alert prompt multiple times ask for login on google chrome

### ISSUE THREAD

**Issue by CITAcadAppsSupport** [OpenCerts/admin-website#160]
this happen when choosing wallet legder network to ropsten - test

during issuing certificate chrome always prompt to sign in, i confirmed the transaction on device token, and saw another alert about take action on security key, at the end the transaction did not successful.

 please refer attached photo. 

regards,
![2](https://user-images.githubusercontent.com/50308837/67370980-37281880-f5ae-11e9-8ebd-f75d25845108.png)
![1](https://user-images.githubusercontent.com/50308837/67370982-37281880-f5ae-11e9-83fe-e7c113e610bb.png)

**Comment by rjchow** [comment]
use chrome

**Comment by CITAcadAppsSupport** [comment]
i am using chrome

**Comment by rjchow** [comment]
that’s a windows dialog not a browser dialog

**Comment by CITAcadAppsSupport** [comment]
hmm you are right, this alert might be security setting and not caused by browser, i also notice there is a box on right hand corner about confirm transaction on wallet/ledger.

**Comment by rjchow** [comment]
https://support.ledger.com/hc/en-us/articles/360023190873-Fix-for-Windows-10-security-popup

haaaaaaahaha. I think they're working on a fix for it so just have to ignore it for now

**Comment by CITAcadAppsSupport** [comment]
thank for the info
