### ISSUE TITLE
How storage api works?

### ISSUE THREAD

**Issue by Rohanashik** [OpenCerts/admin-website#220]
Im asking this here, because last issue was closed because of main problem is solved.

This is the last question
Do we store document in IPFS or Swarm?
https://api-ropsten.opencerts.io/storage/6a86b45b-cb52-4c04-9155-b0d14df30077#db8ea38c4870b15dcc2f545879cd5a60c189e373d0293b9443a063bd29287aca

Where did this files come from, and how this is stored?

**Comment by Nebulis** [comment]
Opencerts doesn't use ipfs or swarm. We use s3.

We have one endpoint to store document and one to get.

**Comment by Rohanashik** [comment]
https://api-ropsten.opencerts.io/storage/#####
In which repo I can see this code?

**Comment by Nebulis** [comment]
https://github.com/OpenCerts/opencerts-functions
