### ISSUE TITLE
Unable to issue certificate batch using Metamask (for UAT)

### ISSUE THREAD

**Issue by seab-gov** [OpenCerts/admin-website#250]
Hi OpenCerts team,

We are unable to issue certificate batch using Metamask as the page is not responsive after click on Issue button,
This is for UAT but user needs to do UAT urgently.
Please advise.

Thanks.

![image](https://user-images.githubusercontent.com/55369878/85491533-4dd3b300-b606-11ea-92f2-cc9d1a227510.png)

**Comment by Nebulis** [comment]
Can you open the developer console and see whether an error is fired?

**Comment by seab-gov** [comment]
Hi,

Attached is the image from dev console FYR.
![image](https://user-images.githubusercontent.com/55369878/85662862-fe1ae780-b6ea-11ea-95d3-bf695ccaee63.png)

FYI, we used this Metamask account to published to UAT before

**Comment by Nebulis** [comment]
Can you copy the document document and a merkle root hash ?

**Comment by seab-gov** [comment]
can it be sent via email? as it is used by SEAB for UAT and we dont want everyone to see it

**Comment by Nebulis** [comment]
I don't get your point?

- Document store is a public info (hard to guess/find)
- Merle root is just a hash with not data at all
- it's a test environment

**Comment by seab-gov** [comment]
document store is store address?

**Comment by Nebulis** [comment]
Yes

**Comment by seab-gov** [comment]
Store address:    0xeDe1B6Fc03f1a9C6905C93a2fceb06E19624a55E
Merkle Root:      0x693f7aaeddb224bdc902b4c584b369e3072dacdc006c37079a5e3aba826ddfa9

**Comment by Nebulis** [comment]
From https://ropsten.etherscan.io/address/0xeDe1B6Fc03f1a9C6905C93a2fceb06E19624a55E#readContract I can see that 0x693f7aaeddb224bdc902b4c584b369e3072dacdc006c37079a5e3aba826ddfa9 has already been issued

![image](https://user-images.githubusercontent.com/503185/86083496-01d4b280-bacd-11ea-899f-44dbd8909058.png)

**Comment by seab-gov** [comment]
the other day we tried, but the cert is not valid. can i check when it is issued?
possible to provide date and time?

**Comment by Nebulis** [comment]
so I used https://ropsten.etherscan.io/address/0xeDe1B6Fc03f1a9C6905C93a2fceb06E19624a55E#readContract

and getIssuedBlock function

which gives me 5279052

which is https://ropsten.etherscan.io/block/5279052

which has been mined 461 days ago

**Comment by Nebulis** [comment]
Transaction hash => https://ropsten.etherscan.io/tx/0x863b6d41e1b1d34a4a6fa01c0df963d18392e4c0414f6da07e3855f3c3bef4b3

**Comment by seab-gov** [comment]
This file has only been published this week. I attached the opencert file here for your reference. it can't be viewed online at https://dev.opencerts.io/

[881.zip](https://github.com/OpenCerts/admin-website/files/4855120/881.zip)

**Comment by rjchow** [comment]
those two certs are under the merkleRoot of 0x920ea6e7e5e49986b1dfa696658ff7316eb35ac83ee27bf4c21dde0628b426a3 which has not been issued, where did 0x693f7aaeddb224bdc902b4c584b369e3072dacdc006c37079a5e3aba826ddfa9 come from?
