### ISSUE TITLE
Insufficient ethers in wallet for deploying new

### ISSUE THREAD

**Issue by instituteofblockchain-tech** [OpenCerts/admin-website#270]
![image](https://user-images.githubusercontent.com/69007042/89397792-de8fc980-d742-11ea-94c3-b5bc2511f8af.png)

**Comment by Nebulis** [comment]
Did you use metamask ? what was the transaction price ? :)

**Comment by lanlan3322** [comment]
the authorization window never show up.

**Comment by Nebulis** [comment]
What network? Did you try once or multiple times? Did you try today?

**Comment by lanlan3322** [comment]
main network. tried just now. same error.
Once the deploy button pressed the error message on the right top corner pops up immediately.

**Comment by Nebulis** [comment]
Looks like there is some checks done and a threshold is set to run or not the transaction.

I will investigate if these checks are needed or can be removed

**Comment by Nebulis** [comment]
it should be fixed, could you try again ?

**Comment by lanlan3322** [comment]
it is working now. Thanks
