### ISSUE TITLE
Next issue page cannot be loaded when accessing OpenCerts Admin Portal with Metamask

### ISSUE THREAD

**Issue by Pat-Goh** [OpenCerts/admin-website#276]
Hi OpenCerts team,

I was accessing OpenCerts Admin Portal in Chrome with Metamask selected but the next issue page cannot be loaded while stuck in the page with spinning "hourglass".  Please advise.

Thank you.

**Comment by Nebulis** [comment]
Hi,

- Can you show us a screenshot of the page that is stuck ?
- Can you open developer tools (the shortchut depends on the OS https://developers.google.com/web/tools/chrome-devtools) and show us a screen shot if any error happens ? (in red)

**Comment by Pat-Goh** [comment]
Screen capture:
![OC-Admin1](https://user-images.githubusercontent.com/48708518/90498342-c2e0e600-e17a-11ea-9bbe-5d73cbf3da1a.png)

Chrome console:
![OC-Admin2](https://user-images.githubusercontent.com/48708518/90498214-99c05580-e17a-11ea-8595-74f2e0e31516.png)

**Comment by Nebulis** [comment]
Hum ok I can't connect anymore as well. Metamask probably changed something I will have to investigate. In the meantime we have a [cli](https://github.com/Open-Attestation/open-attestation-cli) that provides the same functionnality

**Comment by Nebulis** [comment]
Hi,

I found out there were a metamask bug => https://github.com/MetaMask/metamask-extension/issues/9245

But I found a way to get rid of the problem. It should work now.
