### ISSUE TITLE
Cannot issue with Ledger Nano

### ISSUE THREAD

**Issue by ccewuz** [OpenCerts/admin-website#311]
Our user complained that she is unable to issue certs with Ledger Nano on https://admin.opencerts.io today. When she clicked on Issue nothing had happened. She was able to until yesterday. Has any update been made to the website? How can we solve this?

![image](https://user-images.githubusercontent.com/47135828/104685082-3c363200-5735-11eb-8ccc-9b38accbc819.png)

**Comment by Nebulis** [comment]
Hi,

No changes has been made to the admin portal. Another user reported problem to issue using ledger as well: https://github.com/OpenCerts/opencerts-website/issues/588

We provided an alternative flow to use ledger through metamask in the issue.

Let me know if it helps you.

**Comment by ccewuz** [comment]
Hi, Thanks for advice.

We have tried the recommendation in #588 but failed. We managed to add ledger nano into metamask hardware wallet and it can show up in admin website. However, issuance still cannot carry on.

![image](https://user-images.githubusercontent.com/47135828/104870905-a1339700-5984-11eb-9db9-b235dd14361f.png)

**Comment by ccewuz** [comment]
Yes, the hardware is showing "Contract Data Allowed" already

**Comment by Nebulis** [comment]
Can you record the problem ?

**Comment by ccewuz** [comment]
How to record the problem? The balance is equivalent to around $100, so should be enough to pay for one transaction.

**Comment by Nebulis** [comment]
you can use whatever tool that record part of the screen, there is one with window 10 for instance: https://www.laptopmag.com/articles/how-to-video-screen-capture-windows-10

**Comment by ccewuz** [comment]
Please check out the recorded video uploaded. We tried a few times but no luck.


[OpenCerts_Metamask2.zip](https://github.com/OpenCerts/admin-website/files/5876942/OpenCerts_Metamask2.zip)

**Comment by rjchow** [comment]
That particular merkle root has already been issued

![image](https://user-images.githubusercontent.com/27843274/105934770-c2366f00-608b-11eb-80e9-ff5d719d5b7b.png)

**Comment by rjchow** [comment]
![image](https://user-images.githubusercontent.com/27843274/105934818-db3f2000-608b-11eb-8881-7f8c9b220126.png)

**Comment by ccewuz** [comment]
Yes, the user has verified that it's been issued. I guess the transaction had taken too long time so she thought it failed. Thank you for all your efforts. I will close it.
