### ISSUE TITLE
Unable to revoke OpenCert file

### ISSUE THREAD

**Issue by seab-gov** [OpenCerts/admin-website#335]
Hi Helpdesk,

We wanted to report on the issue when trying to revoke OpenCert file. After clicking on Revoke button, the page refreshed and confirmation done in the Nano Ledger to confirm the revoke, however, there are no indication that it is successfully revoked.

Attached is the screen capture for your reference.
![image](https://user-images.githubusercontent.com/55369878/117740343-d2d1b600-b232-11eb-93da-12a480de8673.png)

**Comment by Nebulis** [comment]
Could you share your document store ? plain text :)

**Comment by Nebulis** [comment]
The transaction has been mined

**Comment by seab-gov** [comment]
hi SiaChenRen,
When you said 4 transactions, do you mean that we will be charged 4 times for the same hash no?

hi Nebulis,
When you said it has been mined, does it mean that the revoke transaction is completed?

**Comment by Nebulis** [comment]
Hi,

You can check https://etherscan.io/address/0xe4a94ef9c26904a02cd6735f7d4de1d840146a0f, the 4th transaction from the top worked, the 3 following failed because the document was already revoked.

Yes you have been charged 4 times (for each transaction)

**Comment by SiaChenRen** [comment]
hi @seab-gov, 

Yes, you will be charged 4 times for the same hash. However, the term of the gas price will be different as they are charged based on the computational power. The first transaction is executed completely and revoke the transaction compared to the next three transactions that failed partially. This is the reason that the gas fee for the first transaction has a higher gas fee compared to the next three transactions that failed (gas fee are charged till the point where error occurs)
