### ISSUE TITLE
Unable to access to admin website for production

### ISSUE THREAD

**Issue by laykoonjune** [OpenCerts/admin-website#344]
Hi, 

My user reported that they are unable to login to admin website it shows that admin address wallet not found. 
We are still able to use it on last monday. Please help to check ASAP. Thanks.
![image](https://user-images.githubusercontent.com/46921398/121141135-37e9ed00-c86d-11eb-870e-999b4299fe7a.png)

**Comment by Nebulis** [comment]
Hi, there is a bug in chrome 91 so we had to make a fix yesterday. It works on Chrome but now it doesn't work on firefox.

Use chrome for the moment

**Comment by laykoonjune** [comment]
Hi, my user try on chrome and edge is not working.

**Comment by Nebulis** [comment]
what version of chrome ?

**Comment by laykoonjune** [comment]
![image](https://user-images.githubusercontent.com/46921398/121161366-7f797480-c87f-11eb-8a7f-f166147dfc52.png)

**Comment by Nebulis** [comment]
In the meantime, users can use ledger through metamask => https://docs.opencerts.io/docs/admin-website

**Comment by laykoonjune** [comment]
Version 91.0.4472.77

**Comment by Nebulis** [comment]
Hum, I don't see ny reason it doesn't work as we fixed yesterday for this version. Ask the user to refresh or to use the alternate flow above

**Comment by laykoonjune** [comment]
I will get my user to try and update you if there are any issue face

**Comment by laykoonjune** [comment]
My users are not comfortable to use metamask due to the recently cases of ether beings stolen hence please help to fix it asap as we will need to re issue some opencerts. thanks.

**Comment by SUSS-CITS** [comment]
Hi, I have the same issue too, that admin address wallet not found despite connected. Both Firefox and Google Chrome doesn't work. 
Google Chrome version: 91.0.4472.77
Firefox version: 89.0

Metakmask also doesn't work for me when I was trying to issue out one of the batches. 

FYI, i'm doing testing and is using Ropsten network. Few weeks ago, my user was using the Production network and it is working fine.

**Comment by Nebulis** [comment]
Send an har from the page load to the failure

**Comment by simboonlong** [comment]
exact issue stems from https://github.com/LedgerHQ/ledgerjs/issues/607

https://admin.opencerts.io -> latest chrome should work
https://firefox.admin.opencerts.io -> firefox should work

note that these are interim solutions, the ideal usage is to connect hardware ledger via metamask -> https://docs.opencerts.io/docs/admin-website

**Comment by SUSS-CITS** [comment]
@simboonlong thank you. I tried https://firefox.admin.opencerts.io and it is working.

**Comment by jacelee2000** [comment]
hi,
I am trying to access the admin opencerts link below via metamask and unable to access. As we need to go through UAT, we use the metamask to publish certificate for UAT purpose. Please advise urgently. thank you.

https://github.com/OpenCerts/admin-website/issues/344

**Comment by jacelee2000** [comment]
to add on, I did try using firefox but issue not resolved. 
![metamask](https://user-images.githubusercontent.com/22413292/135952165-c85a4085-5774-48ac-a1e6-918ad65c46ff.PNG)

**Comment by simboonlong** [comment]
the url u tried on is a netlify preview url. using firefox browser, can try on https://firefox.admin.opencerts.io instead?

**Comment by jacelee2000** [comment]
We use for UAT purpose. The link given is production url. I suppose we can't use it for UAT purpose. Furthermore, same issue occur using the url given.
https://firefox.admin.opencerts.io/deploy

![image](https://user-images.githubusercontent.com/22413292/135954907-6d075644-4b4b-49c8-b17f-d153e86fc10d.png)

**Comment by simboonlong** [comment]
tried issuing on chrome with metamask, works fine

<img width="1313" alt="issue" src="https://user-images.githubusercontent.com/4774314/135958940-1cff2b80-3e28-47da-a0bd-4dbaec6aaead.png">
<img width="1358" alt="verified" src="https://user-images.githubusercontent.com/4774314/135958949-b3f36606-fe2b-4011-9ea5-acb1ebaec03f.png">

**Comment by Nebulis** [comment]
You can use both url in uat / prod.

The kind of metamask account (ropsten / mainnet) determine whether it's prod or not

**Comment by jacelee2000** [comment]
I tried access using chrome using the https://admin.opencerts.io url but unable to access. My Chrome version as below.
![image](https://user-images.githubusercontent.com/22413292/135967567-ad9e44ea-9963-40e6-9d89-0db890ca6736.png)

**Comment by Nebulis** [comment]
> You can use both url in uat / prod.
> 
> The kind of metamask account (ropsten / mainnet) determine whether it's prod or not

As mentioned above there is no such thing called uat

So you tried the 4 combination?
What's the error in the console?

**Comment by jacelee2000** [comment]
there is no error. I recall I highlighted this issue before in spectrum chat to access https://admin.opencerts.io using Chrome (use nano ledger) have same issue also. You mentioned to use firefox to access via https://firefox.admin.opencerts.io url. It solve the issue. 
However, when I access via Chrome and Firefox as advise base on 2 url above via metamask, the same issue occur where unable to load to the publish certificate page.

Chrome
![image](https://user-images.githubusercontent.com/22413292/136130128-0aeb3891-af30-4adb-adda-e75ef9fdc85b.png)

Firefox
![image](https://user-images.githubusercontent.com/22413292/136130583-ffab8595-44a7-4ebf-a02b-30e57886d7b7.png)

**Comment by Nebulis** [comment]
I could do it, but that also required you to give me your private key, otherwise i won't be able to publish to your certificate store

Did you try the CLI?

**Comment by jacelee2000** [comment]
if no, please advise how do we go about publishing the certificate.

what CLI do you mean?

**Comment by Nebulis** [comment]
https://github.com/Open-Attestation/open-attestation-cli

I'm trying to find internally someone for who metamask fails, unsuccessfully for the moment

**Comment by simboonlong** [comment]
tried again and still works, documentating it:

https://user-images.githubusercontent.com/4774314/136317699-3016f759-731f-4855-8657-7ddc17812e40.mp4

in this example, for a start maybe can check if the document store address is in the txt records of the domain name where your renderer is sitting at. can use https://toolkit.openattestation.com/dns to check. make sure this document store address was deployed previously with the same wallet metamask account, otherwise you cannot issue.

then use `merkleRoot` value to issue

reading and understanding the docs takes about a day, the most 2. if short of time, as mentioned can read only the document store cli portion and figure what you need to do. once understood, deploying and issue takes less than half a day

**Comment by jacelee2000** [comment]
I tried by downgrade the chrome in my personal pc to 91.0.04472.77, also unable to access the https://admin.opencerts.io/ url

**Comment by simboonlong** [comment]
in the example above was Chrome Version 94.0.4606.71.  https://admin.opencerts.io is a publicly accessible website. do you happen to have some other browser extensions installed? if so, try disabling them to see if any caused the url to be inaccessible first?

**Comment by Nebulis** [comment]
yes

**Comment by Nebulis** [comment]
Hi @jacelee2000 did you manage to fix the problem?
