### ISSUE TITLE
New Ledger token

### ISSUE THREAD

**Issue by SP-INDT-OpenCert** [OpenCerts/admin-website#356]
Hi,

Just need to confirm about this, our ledger token LCD is unreadable right now.
Importing the current seed phrase to the new ledger token should be enough? 
No any other action item should be taken? I'm worried about the smart contract but I think it's tied to the wallet address so shouldn't be any issue... I just want to confirm my understanding.

Thanks!

**Comment by Nebulis** [comment]
Looks fine to me. Maybe you can check with ledger as instructed in their documentation https://support.ledger.com/hc/en-us/articles/4404388633489-Export-your-accounts?docs=true

the smart contract is bound to the wallet, no action is needed

**Comment by SP-INDT-OpenCert** [comment]
Thank you, managed to import the wallet in the new token but haven't actually tested yet as the business users doen't have any pending certs to publish, but the wallet & funds are ok. One thing I observe as I compare from the previous set-up is that I can't find the Display Contract Data in the settings for ETH, could have been due to the latest firmware??

**Comment by Nebulis** [comment]
Good news.

I'm not sure about the display contract data setting. I couldn't find anything. The best is to contract ledger support
