### ISSUE TITLE
Can't issue cert using metamask - Ropsten test network 

### ISSUE THREAD

**Issue by RP-OIS-SK** [OpenCerts/admin-website#368]
I try to issue cert using metamask - Ropsten test network but there is no popup to confirm the transaction. 

Refer to screenshot. 

I have no issue when using windows - chrome but have problem in  Mac - chrome
macOS 11.6, Chrome - Version 97.0.4692.99 

store id : 0x061aFcFF60b90E0F633F8ef157e01BaB9b2FfDD3 
merkleRoot: 0xbc529b177128ad741a2583cea1d91e3cf6a0da06e64b8f81df56c836b6958085

I noticed that after I installed the metamask, it worked for the first time and after that it does not work.  
I have tried uninstalled and reinstalled again, but it did not work.  

Please advise.

**Comment by RP-OIS-SK** [comment]
<img width="1440" alt="Screenshot 2022-01-21 at 10 57 08 PM" src="https://user-images.githubusercontent.com/47696120/150549920-1d57eaae-de89-4b84-8a35-208caea8dc35.png">

**Comment by RP-OIS-SK** [comment]
<img width="1314" alt="Screenshot 2022-01-21 at 10 55 37 PM" src="https://user-images.githubusercontent.com/47696120/150550123-c496d101-75d2-448c-afa4-969d5f3c242e.png">

**Comment by RP-OIS-SK** [comment]
HI Team, 

Any update on this ?

**Comment by RP-OIS-SK** [comment]
![image](https://user-images.githubusercontent.com/47696120/151283109-3ca71aba-a67f-4eb1-b097-ec315948a2ed.png)
It seemed on the windows we are getting the same issue.

**Comment by RP-OIS-SK** [comment]
same issue with Firefox on the admin.opencerts.io and newadmin.opencerts.io

**Comment by RP-OIS-SK** [comment]
Any update ?

**Comment by simboonlong** [comment]
not sure what's needs to be done. in the later screenshot, the error message -> `Only hashes that have not been issued can be issued`

referring to https://ropsten.etherscan.io/address/0x061aFcFF60b90E0F633F8ef157e01BaB9b2FfDD3#events, `0x43e6a0fc3a21ebcc986f04ab783946185bf074e3` has already issued merkleRoot `0x7bef9c1ef96de75281abe9546e09dfc674448a1292539b32bbf0539d371b067e`

**Comment by RP-OIS-SK** [comment]
Thank you for the explanation.

**Comment by RP-OIS-SK** [comment]
I have verified it is working now
