### ISSUE TITLE
admin.opencerts.io and new.admin does not work for Ropsten test network 

### ISSUE THREAD

**Issue by RP-OIS-SK** [OpenCerts/admin-website#373]
new.admin.opencerts.io can't connect to metamask.   

admin.opencerts.io connected to metamask for Ropsten network but not working for account balance,  issue cert etc. 

dev.opencerts.io is not working also.  The same cert was working previously and are not working now.  

![image](https://user-images.githubusercontent.com/47696120/194979300-8346a40b-8682-45c8-a45d-c3353a152596.png)

Please advise.  

All sites setting already turned on. 
![image](https://user-images.githubusercontent.com/47696120/194978286-dd63034a-8ed0-450f-b06d-89aa99f6c294.png)

**Comment by zixiang2018** [comment]
Hi @RP-OIS-SK , we are shifting to Goerli testnet as Ropsten tesnet is deprecated. We will require you to add a create a new document store in Goerli testnet and send the document store address to us.


Please email us at openattestation_support@tech.gov.sg using your official email address (e.g. xxx@rp.edu.sg). Also, do mention in the email about the request to add the new document store address in Goerli. Thank you!


You can refer to this issue for more info - https://github.com/OpenCerts/opencerts-website/issues/685
