### ISSUE TITLE
Error in addon.cpp

### ISSUE THREAD

**Issue by ryansena** [OpenCerts/admin-website#46]
c:\users\common\downloads\admin-website-master\node_modules\sha3\node_modules\nan\nan.h(839): warning C4996: 'node::MakeCallback': was declared deprecated (compiling source file ..\src\addon.cpp) [C:\Users\Common\Downloads\admin-website-master\node_modules\sha3\build\sha3.vcxproj]
  c:\users\common\.node-gyp\10.15.0\include\node\node.h(176): note: see declaration of 'node::MakeCallback' (compiling source file ..\src\addon.cpp)
c:\users\common\downloads\admin-website-master\node_modules\sha3\node_modules\nan\nan.h(854): warning C4996: 'node::MakeCallback': was declared deprecated (compiling source file ..\src\addon.cpp) [C:\Users\Common\Downloads\admin-website-master\node_modules\sha3\build\sha3.vcxproj]
  c:\users\common\.node-gyp\10.15.0\include\node\node.h(169): note: see declaration of 'node::MakeCallback' (compiling source file ..\src\addon.cpp)
c:\users\common\downloads\admin-website-master\node_modules\sha3\node_modules\nan\nan.h(869): warning C4996: 'node::MakeCallback': was declared deprecated (compiling source file ..\src\addon.cpp) [C:\Users\Common\Downloads\admin-website-master\node_modules\sha3\build\sha3.vcxproj]
  c:\users\common\.node-gyp\10.15.0\include\node\node.h(162): note: see declaration of 'node::MakeCallback' (compiling source file ..\src\addon.cpp)
c:\users\common\downloads\admin-website-master\node_modules\sha3\node_modules\nan\nan.h(1648): warning C4996: 'node::MakeCallback': was declared deprecated (compiling source file ..\src\addon.cpp) [C:\Users\Common\Downloads\admin-website-master\node_modules\sha3\build\sha3.vcxproj]
  c:\users\common\.node-gyp\10.15.0\include\node\node.h(176): note: see declaration of 'node::MakeCallback' (compiling source file ..\src\addon.cpp)
c:\users\common\downloads\admin-website-master\node_modules\sha3\src\addon.cpp(49): warning C4316: 'SHA3Hash': object allocated on the heap may not be aligned 32 [C:\Users\Common\Downloads\admin-website-master\node_modules\sha3\build\sha3.vcxproj]
**c:\users\common\downloads\admin-website-master\node_modules\sha3\src\addon.cpp(59): error C2661: 'v8::Function::NewInstance': no overloaded function takes 2 arguments** [C:\Users\Common\Downloads\admin-website-master\node_modules\sha3\build\sha3.vcxproj]
c:\users\common\downloads\admin-website-master\node_modules\sha3\src\addon.cpp(36): warning C4996: 'v8::Value::Int32Value': was declared deprecated [C:\Users\Common\Downloads\admin-website-master\node_modules\sha3\build\sha3.vcxproj]
  c:\users\common\.node-gyp\10.15.0\include\node\v8.h(2478): note: see declaration of 'v8::Value::Int32Value'
c:\users\common\downloads\admin-website-master\node_modules\sha3\src\addon.cpp(97): warning C4996: 'v8::Value::ToObject': was declared deprecated [C:\Users\Common\Downloads\admin-website-master\node_modules\sha3\build\sha3.vcxproj]
  c:\users\common\.node-gyp\10.15.0\include\node\v8.h(10046): note: see declaration of 'v8::Value::ToObject'
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Common\Downloads\admin-website-master\node_modules\sha3

**Comment by rjchow** [comment]
Probably a windows issue can you try https://github.com/nodejs/node-gyp#on-windows
