### ISSUE TITLE
red color font on store address 

### ISSUE THREAD

**Issue by bapuy** [OpenCerts/admin-website#52]
Hi, 

i tried to issue certificate using ropsten(with device) environment, but no response from the web, and i noticed the font is red instead of green color.
![2019-03-28_1320](https://user-images.githubusercontent.com/4141785/55132275-c8d8c000-515c-11e9-8bb4-874f7a68d71c.png)

**Comment by rjchow** [comment]
we recently introduced a case-sensitive address verification algorithm, can you try using '0x3f43FB8546E97b2c1D5eD087767C0d2eb2e13f8b' for your store address and let me know how it goes?

**Comment by bapuy** [comment]
is same, still red color.

0x3f43FB8546E97b2c1D5eD087767C0d2eb2e13f8b

**Comment by rjchow** [comment]
suspect there's a colouring bug, could you try submitting the transaction and see if it works?

**Comment by bapuy** [comment]
tried to issue, and is not working, the button "issueing..." back to "issue" after around 20 seconds.

https://ropsten.etherscan.io/address/0x3934c12F32A2112DE7e89BE7AeCCc7d2F8ebB1C5

**Comment by rjchow** [comment]
anything in your browser's console?

**Comment by rjchow** [comment]
some obvious mistakes I often make:
- forgot to unlock the ledger nano
- forgot to go into the ethereum app on the ledger nano
- forgot to confirm the transaction on the ledger nano

can you check that you've done these too?

**Comment by bapuy** [comment]
yup.

1. check ETH balance : 2.99451361 Ether https://ropsten.etherscan.io/address/0x3934c12F32A2112DE7e89BE7AeCCc7d2F8ebB1C5
2. unlock ledger nano, and go to ethereum app
3. issue certificate at admin page, confirm transaction on ledger nano.
   there are 3 confirmation:
   1. confirm selector
   2. confirm parameter
   3. confirm transaction.

page response "issuing" to "issue"


attached  browser's console
![02](https://user-images.githubusercontent.com/4141785/55138964-9d130580-516f-11e9-85a4-ecabe1b4d905.png)

**Comment by rjchow** [comment]
i just created a build here with better debugging information, can you try using this and let me know what you see in the console? thanks

https://5c9c7ae87ff43a000856dec8--admin-opencerts.netlify.com/

**Comment by bapuy** [comment]
issued and it works, batch has been issued:
https://ropsten.etherscan.io/tx/0x80b9ec3e477a9ea64b14232149507a796a8fcfd0d61dc2df75e59ceaa3d4daae

console: 
[01.txt](https://github.com/OpenCerts/admin-website/files/3016911/01.txt)
![04](https://user-images.githubusercontent.com/4141785/55142253-267a0600-5177-11e9-8fe6-d6ce5c851c31.png)

**Comment by rjchow** [comment]
interesting error, will investigate. good to know its working for you, we will push this build to production shortly
