### ISSUE TITLE
Cannot Deploy new instance 

### ISSUE THREAD

**Issue by RP-OIS-SK** [OpenCerts/admin-website#63]
HI, 

When click on the Deploy button, the transaction appear on the Ledger Nano S. When I confirm the transaction on the Ledger Nano S, nothing happen in the admin.opencerts.io page.   

Please advise. 

Windows 10 Enterprise 1803 
Chrome Version 74.0.3729.16
Ledger firmware 1.5.5
Ethereum 1.2.7

Thanks and regards,
SK

**Comment by rjchow** [comment]
Can you make a video showing what you did?

**Comment by RP-OIS-SK** [comment]
I have sent the video link to your email account.

**Comment by rjchow** [comment]
I don't see any ether in your address https://etherscan.io/address/0x6a6B4cEB32990A5E1186e92b9E1ecd7193Fd35f1

have you transferred the ether to the right address?

**Comment by RP-OIS-SK** [comment]
The address appeared in the Ledger Live > Receive is different from admin.opencerts.io.   The Ether can transfer to the one show Ledger Live.  

So we should only send to that in admin.opercerts.io ?  
we can only check the value using Etherscan as Ledger Live will not display that address ?

**Comment by rjchow** [comment]
refer to this thread with the same issue https://github.com/OpenCerts/admin-website/issues/64

**Comment by rjchow** [comment]
Won't have access to tech.gov.sg till Monday, there shouldn't be any
sensitive info in the recording?

**Comment by RP-OIS-SK** [comment]
No. You have already answered by question.  Thanks.
