### ISSUE TITLE
Deploying new store address

### ISSUE THREAD

**Issue by ryansena** [OpenCerts/admin-website#64]
Now we have installed Ledger Live and linked the account to our test token with its own ETH address (0xC2Dcf15030Fd5EB533904e1873F965618dA3ACD4), we also transferred funds to this address via Coin Base.

When we do deployment via the admin function no pop-up window, looking at the initialization procedure, it says we use the ETH address from the admin page instead (0x51b4121D0Dd433a3Cfbb98eE591E982C27Db1db5), are we supposed to send funds to this ETH address not the one indicated in the token?

How do we manage the fund from this ETH address in the Ledger Live?

**Comment by rjchow** [comment]
Yes please send to the ETH address indicated on our admin site
You can access this wallet via https://www.myetherwallet.com if necessary but you shouldn't need to

**Comment by ryansena** [comment]
I did sent the amount to the admin's ETH address (https://etherscan.io/tx/0xa8dd8140b600b36f0f7dc7eeec10dce02175524a9006fe9570406195f35a4dca)

Ropsten acct link from your admin page however shows no funds.
https://ropsten.etherscan.io/address/0x51b4121D0Dd433a3Cfbb98eE591E982C27Db1db5

But upon clicking deploy, nothing is happening.. no-pop-up.

**Comment by rjchow** [comment]
I'm not really sure I understand the situation here
Ropsten is completely separate to main net, it's for testing purposes. Sending funds to main net address will not result in funds showing up on ropsten

If you're deploying on main net using real ethers, use the ledger main net option

**Comment by ryansena** [comment]
For testing, I already done the Metamask, it worked smoothly.

Now we're doing the creation of store address using the actual tokens which will be for UAT & Production. I sent funds using to the ETH address given for Ledger Nano (Ropsten), i don't see anything upon clicking deploy. I don't even know where did my funds go and how can i get it back? :/

Now i need to transfer again to the ETH address for Ledger Nano (Mainnet), my concern is if I have the same issue as Ropsten then i lost both funds.

**Comment by rjchow** [comment]
Don't need to send funds again because the ledger main net and ledger ropsten address are deterministically derived from your ledger nano hardware wallet, so actually you've already transferred funds to the main net address as you can see here

https://etherscan.io/address/0x51b4121d0dd433a3cfbb98ee591e982c27db1db5

**Comment by ryansena** [comment]
That's good to hear, but it brings back to the same problem, I tried deploying using Mainnet and it just go to Deploying then back to Deploy button.

Another thing, this ETH address from the admin site will be the same address every time we issue certificate, it means we just keep track this address?

**Comment by rjchow** [comment]
current gas price is a bit higher than normal, we're working on providing better feedback for insufficient gas errors please bear with us

in the meantime, 0.05 eth should be enough for this transaction to happen

yes this is the address you will put into the registry and you will always issue from this address

**Comment by yehjxraymond** [comment]
test

**Comment by rjchow** [comment]
Don't need to send funds again because the ledger main net and ledger
ropsten address are deterministically derived from your ledger nano
hardware wallet, so actually you've already transferred funds to the main
net address as you can see here

https://etherscan.io/address/0x51b4121d0dd433a3cfbb98ee591e982c27db1db5

**Comment by ryansena** [comment]
Our users was able to send funds and is now 0.052 ETH
https://etherscan.io/address/0x51b4121d0dd433a3cfbb98ee591e982c27db1db5

But still the same issue, nothing is happening after clicking deploy.
Is the fund sufficient?

**Comment by yehjxraymond** [comment]
Can you take a screenshot of the state before you click on deploy?

**Comment by ryansena** [comment]
As requested:
https://drive.google.com/open?id=1-z80K1BTDVXV7lw1681b93kTmnqoMkZo

**Comment by yehjxraymond** [comment]
If you see the metamask icon, you can see a (1) alert there. Could you click on the metamask to see if there is a notification to ask you to confirm the transaction?

**Comment by ryansena** [comment]
Oh.. that one only asks me to log-in... i logged out of Metamask as I'm not using it now.
I'm using Mainnet so I assume it won't trigger any metamask transactions.

**Comment by yehjxraymond** [comment]
Hmm you have a very strange issue... Could you open the browser console and see if there is any logs there?

**Comment by yehjxraymond** [comment]
Also, can you check that:
1. you are in the ethereum app
2. you have enabled "contract data" in the settings of the ethereum app
3. you have enabled the "display data" in the setting of the ethereum app

**Comment by ryansena** [comment]
Settings looks ok, here's what I did this time. I just turned off the Metamask (extension) and tried again.
A confirmed the transaction from the token, and transaction seems to proceed as I can see funds had been deducted already:
https://etherscan.io/address/0x51b4121d0dd433a3cfbb98ee591e982c27db1db5

But the admin site is stuck to **Deploying** for more than 5mins now, nothing is shown in the console log.

**Comment by yehjxraymond** [comment]
Interesting... we are working on a better interface to solve issues like this.

In the meanwhile, good to see that you got your store up. The store address is 0x73eee54e79f7b909c12a220187ec8705b1baa011

The contract can be found:
https://etherscan.io/address/0x73eee54e79f7b909c12a220187ec8705b1baa011#readContract

Curious.. why is the name Singapore Polytechnic PET (TEST) ?

**Comment by ryansena** [comment]
Thanks for the info, business users still deciding on how to consolidate these stuffs.
Basically we have PET (Full time students) and CET (Continuing Education or Short Courses) both are in 2 different systems, maintained and owned by different departments.

As for the TEST, well i do the initial set-up to handle issues/cases like these so I can guide them when they do the actual PROD token/store.

**Comment by rjchow** [comment]
Apologies for the rough edges around this project -

If its not too much trouble do you mind sharing your documentation of your learnings / this process?
That'll help us improve our user experience going foward

**Comment by ryansena** [comment]
Oh i dont mind sharing.. No offence I find the guide really lacking some detailed info especially for us who were not familiar with cryptocurrency stuffs.. Will send it by this week ;)

**Comment by ryansena** [comment]
Please check this guide/doc, hopefully other institutions can find this useful:
https://drive.google.com/open?id=1eaBEQwOe05dt7T5GbZo1UGOYmAMTJGRT
