### ISSUE TITLE
Unable to retrieve Current Account

### ISSUE THREAD

**Issue by ryansena** [OpenCerts/admin-website#67]
I was able to pull the current account in deploying new store address last week but the funds are not enough. Now I'm trying to deploy again but this time the current account is now showing been refreshing for couple of minutes now.

Token is inserted and not locked.
I also tried both while being logged and not logged in Ledger Live

**Comment by rjchow** [comment]
the code hasn't changed between last week and now, has your environment changed?
which browser are you using?

**Comment by ryansena** [comment]
I'm using the same machine, browser, network and token as to last friday's issue (https://github.com/OpenCerts/admin-website/issues/64).

Since it's a funding issue, i wanted to make sure that the same ETH address will be provided by the admin site before sending the funds, unfortunately no address is being shown, i already done a restart twice.

**Comment by ryansena** [comment]
Strange, now after lunch the current account is now showing, I have to navigate to Ethereum > Use wallet to view accounts in the token, then click refresh on the admin site. Not sure if that really solve the issue.

**Comment by rjchow** [comment]
yea that's actually intended behaviour - you need to be in the ethereum app

**Comment by ryansena** [comment]
Thanks for the quick response.
